targets:
  $default:
    sources:
      - lib/**
      - appwrite.json
      - $package$
      - pubspec.yaml
    builders:
      appwrite_model_generator:modelBuilder:
        generate_for:
          - appwrite.json
      appwrite_model_generator:exampleJsonBuilder:
        generate_for:
          - appwrite.json
