targets:
  $default:
    sources:
      - lib/**
      - appwrite.json
      - $package$
      - pubspec.yaml
    builders:
      stibu|modelBuilder:
        generate_for:
          - appwrite.json

builders:
  modelBuilder:
    import: 'package:stibu/code_generation.dart'
    builder_factories: [ 'modelBuilder' ]
    build_extensions:
      '.json': ['lib/{{}}.models.dart']
    build_to: source
    auto_apply: dependents
