arb-dir: lib/l10n/arb
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: Lang
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_errors.txt
