name: stibu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.6
  auto_route: ^9.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  logging: ^1.2.0
  url_protocol:
    path: url_protocol
  app_links: ^6.2.0
  fluent_ui: ^4.9.1
  system_theme: ^3.0.0
  appwrite: ^12.0.1
  result_type: ^0.2.0
  bitsdojo_window: ^0.1.6
  get_it: ^7.7.0
  rxdart: ^0.28.0
  collection: ^1.18.0
  html_unescape: ^2.0.0
  http: ^1.2.2
  table_calendar: ^3.1.2
  build: ^2.4.1
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  sanitize_filename: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
