name: stibu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.11
  june: ^1.0.0+1
  auto_route: ^9.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  logging: ^1.2.0
  url_protocol:
    path: url_protocol
  args: ^2.5.0
  multi_instance:
    path : multi_instance

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
