name: stibu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.6
  june: ^1.0.0+1
  auto_route: ^9.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  logging: ^1.2.0
  url_protocol:
    path: url_protocol
  app_links: ^6.2.0
  fluent_ui: ^4.9.1
  system_theme: ^3.0.0
  appwrite: ^12.0.1
  result_type: ^0.2.0
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
