name: appwrite_model_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables:
  modelBuilder:
  exampleJsonBuilder:

environment:
  sdk: ^3.4.3

dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.7
  dart_helper_utils: ^2.7.0
  build: ^2.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
