name: Flutter Build and Release

on:
  push:
    tags:
      - 'v*'    # Only trigger on version tags like v1.0, v1.1, etc.
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Java for Android
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Recommended OpenJDK distribution
          java-version: '11'      # Java version required by Android

      - name: Run dart buildrunner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64

      - name: Upload Android APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run dart buildrunner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows App
        run: flutter build windows --release

      - name: Upload Windows App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/runner/Release/*.exe

  release:
    needs: [android, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Android APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk

      - name: Download Windows App Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-app

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/android-apk/build/app/outputs/flutter-apk/app-release.apk
            ${{ github.workspace }}/windows-app/build/windows/runner/Release/*.exe
